### ISSUE TITLE
switch to HTTP Post

### ISSUE THREAD

**Issue by chlujo** [KiboOst/php-Kodi-jsonAPI#3]
Hi,
any plans to change your code so it sends an http POST? I have been shutting down KODI with an HTTP GET directly from Devolo Home Control but since Leia, Kodi does not accept HTTP GET any more for most of the API commands. As there is no way to do a POST from DHC I googled around and came to your Kodi class. But than I realized that it is doing a GET as well ...
Regards
Chris

**Comment by KiboOst** [comment]
Hi. I didn't test Kodi18 yet and wasn't aware about it not supporting GET anymore.
Anyway, I use this API everyday with Jeedom, and I will switch to 18 sooner or later, I guess I will have to support 18 ;-)

**Comment by KiboOst** [comment]
Hi,
If you have Kodi v18, can you test this API file :
https://github.com/KiboOst/php-Kodi-jsonAPI/blob/master/class/phpKodi-api_v18.php

Every single request with it is now POST. All I tried works perfectly with v17 also, but I don't have v18 installed to test.
