### ISSUE TITLE
Sanity Check on openFile

### ISSUE THREAD

**Issue by ghost** [KiboOst/php-Kodi-jsonAPI#4]
I am using your api and it is most helpful - many thanks. 
However, I have been unable to get the openFile working yet (other methods such as togglePlayPause, getActivePlayer, etc are working fine). 
I am trying this
`$IP = "192.168.1.231:8080";
$_Kodi = new Kodi($IP);
if (isset($_Kodi->error)) die($_Kodi->error);

print_r($_Kodi->openFile("file://Videos/Videos/Trombone.mp4"));`

The output I get is this (after adding an apropriately placed echo in the class). 
{"method":"Player.Open", "params":{"item":{"file":"file%3A%2F%2F%2FVideos%2F%2FVideos%2F%2FTrombone.mp4"}}}Array ( [result] => [error] => Array ( [code] => -32602 [message] => Invalid params. ) )

The equivalent curl command line call works fine

`sudo curl -X POST -H "content-type:application/json" http://192.168.1.231:8080/jsonrpc -d '{"jsonrpc":"2.0","id":"1","method":"Player.Open","params":{"item":{"file":"file://Videos/Videos/Trombone.mp4"}}}'`

**Comment by KiboOst** [comment]
Hi,
This is now fixed.
You can always send whatever json string with $_Kodi->sendJson($jsonString);
Also, you can $_Kodi->setDebug(true); to get lot of debug info when using it.
Thanks for the feedback ;-)

**Comment by ghost** [comment]
Thanks for the fix. Much appreciated. Working well now.
