### ISSUE TITLE
Multiple Instances

### ISSUE THREAD

**Issue by ghost** [KiboOst/php-Kodi-jsonAPI#5]
The use case is for controlling 20 Kodis across the network. 
Can this API support that or be made to support it.

**Comment by KiboOst** [comment]
Hi,
It is a php class, so you can instantiate it as many time as you need. I have three kodi on my network and have interfaced them into Jeedom without any problem. Just create a new instance with its own IP.
$_Kodi = new Kodi($IP);
You can even make an array of your kodis
$_Kodi = array();
$_Kodi['name1'] = new Kodi($IP1);
$_Kodi['name2'] = new Kodi($IP2);
etc
I would set an array of name=>IP and a foreach loop to create them.
